name: Java CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup java
        uses: actions/setup-java@v3
        with:
          java-version: '20'
          distribution: 'oracle'
          cache: 'gradle'

      - name: Build, test and checkstyle
        run: |
          make install
          make test
          make lint

      - name: Generate jacoco report
        run: make report

      - name: Publish Code Climate Test Coverage
        uses: codeclimate/test-reporter-action@v3
        with:
          file: ./build/reports/jacoco/test/jacocoTestReport.xml
          token: ${{ secrets.TEST_REPORTER_ID }}
