name: Java CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup java
        uses: actions/setup-java@v3
        with:
          java-version: '20'
          distribution: 'oracle'
          cache: 'gradle'

      - name: Build, test and checkstyle
        run: |
          make install
          make test
          make lint

      - name: Generate jacoco report
        run: make report

      - name: Publish CodeClimate test coverage
        uses: paambaati/codeclimate-action@v5.0.0
        env:
          CC_TEST_REPORTER_ID: ${{secrets.TEST_REPORTER_ID}}
          JACOCO_SOURCE_PATH: "$app/src/main/java; make-C app report"
